#!/bin/sh
chown -R root:wheel /usr/bin/Sophond
chown -R root:wheel /Library/LaunchDaemons/com.jiaxw.sophond.plist
/bin/launchctl unload /Library/LaunchDaemons/com.jiaxw.sophond.plist
/bin/launchctl load /Library/LaunchDaemons/com.jiaxw.sophond.plist